### ISSUE TITLE
quantum-resistant-lock-script launch testnet

### ISSUE THREAD

**Issue by zhangsoledad** [nervosnetwork/ckb-kanban#1]
Quantum resistant lock script on CKB, using [SPHINCS+](https://github.com/sphincs/sphincsplus).

https://github.com/cryptape/quantum-resistant-lock-script

https://pudge.explorer.nervos.org/transaction/0x35f51257673c7a7edd009fa2166e6f8645156207c9da38202f04ba4d94d9e519

**Comment by XuJiandong** [comment]
done.  See https://github.com/cryptape/quantum-resistant-lock-script
