### ISSUE TITLE
A more asynchronous synchronous solution that separates compute and IO to enable better use of bandwidth

### ISSUE THREAD

**Issue by zhangsoledad** [nervosnetwork/ckb-kanban#16]
PR: https://github.com/nervosnetwork/ckb/pull/4365

**Comment by doitian** [comment]
https://github.com/nervosnetwork/ckb/pull/4365

**Comment by doitian** [comment]
- Released an RC version and started to test it in the testnet environment.
- Improved the bootstrap algorithm when async block downloading starts.

**Comment by doitian** [comment]
Testnet update to ckb-async-download-rc2 on May 13
