### ISSUE TITLE
Spawn Syscall Enhancement

### ISSUE THREAD

**Issue by doitian** [nervosnetwork/ckb-kanban#31]
Investigating a new approach for the spawn syscall. This involves introducing a pipe and deterministic scheduler to facilitate communication between parent and child VM instances. A prototype can be found [here](https://github.com/xxuejie/ckb-vm-deterministic-scheduler).

**Comment by doitian** [comment]
Progress Update:

- Improved the scheduler and finished the testing.
- Started the syscall spawn implementation.

**Comment by xxuejie** [comment]
An implementation for the new spawn is now in review phase: https://github.com/nervosnetwork/ckb/pull/4380

The accompanying RFC changes are also put together: https://github.com/nervosnetwork/rfcs/pull/436

**Comment by doitian** [comment]
Added testing pause/resume API for acceptance for temporary randomize testing: 

https://github.com/chenyukang/ckb/commit/58db12c157da0a44fcf19c515ff9a62641fab292
