### ISSUE TITLE
Indexer exact search mode support

### ISSUE THREAD

**Issue by zhangsoledad** [nervosnetwork/ckb-kanban#7]
Developer now can match the exact script for the query.

https://github.com/nervosnetwork/ckb/pull/3839
https://github.com/nervosnetwork/ckb-indexer/pull/64

- [x] ckb-sdk-rust https://github.com/nervosnetwork/ckb-sdk-rust/pull/55
- [x] ckb-sdk-java https://github.com/nervosnetwork/ckb-sdk-java/pull/627
- [ ] ckb-sdk-go

**Comment by eval-exec** [comment]
`ckb-sdk-go` have implemented indexer search mode:  https://github.com/nervosnetwork/ckb-sdk-go/pull/202
